/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [Id]
      ,[Symbol]
      ,[Date]
      ,[Bid]
      ,[Ask]
      ,[Market]
      ,[FiftyTwoWeekLowChange]
      ,[FiftyTwoWeekLowChangePercent]
      ,[FiftyTwoWeekHighChange]
      ,[FiftyTwoWeekHighChangePercent]
      ,[FiftyTwoWeekLow]
      ,[FiftyTwoWeekHigh]
      ,[FiftyDayAverage]
      ,[FiftyDayAverageChange]
      ,[FiftyDayAverageChangePercent]
      ,[TwoHundredDayAverage]
      ,[TwoHundredDayAverageChange]
      ,[TwoHundredDayAverageChangePercent]
      ,[SourceInterval]
      ,[ExpirationDates]
      ,[Strikes]
      ,[HasMiniOptions]
  FROM [ScanOpts].[dbo].[Quotes]
  WHERE Symbol = 'QQQ'
  ORDER BY Date DESC