SELECT [Id]
      ,[Symbol]
      ,[Date]
      ,[Open]
      ,[High]
      ,[Low]
      ,[Close]
      ,[SMA20]
      ,[StandardDeviation]
      ,[UpperBand]
      ,[LowerBand]
      ,[BandRatio]
      ,[Volume]
      ,[Timestamp]
  FROM [ScanOpts].[dbo].[BollingerBands]
  WHERE Symbol = 'A'
  ORDER BY Date desc